### ISSUE TITLE
Customer Churn Code

### ISSUE THREAD

**Issue by bmitre** [briatte/ida#19]
Dear Matt Dancho:

I am running your Customer Churn code, but am getting the following error, and cannot fix it. Can you help me please? Thank you.

> # Run explain() on explainer
> explanation <- lime::explain(
+   x_test_tbl[1:10,], 
+   explainer    = explainer, 
+   n_labels     = 1, 
+   n_features   = 4,
+   kernel_width = 0.5
+ )
Error in `dimnames<-.data.frame`(`*tmp*`, value = list(n)) : 
  invalid 'dimnames' given for data frame
>

**Comment by briatte** [comment]
Wrong repo?
